# fly.toml app configuration file generated for rzpercussion-site-winter-feather-107 on 2024-12-05T11:13:17-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rzpercussion-site-winter-feather-107'
primary_region = 'ord'
console_command = '/code/manage.py shell'

[build]

[deploy]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="database"
  destination="/mnt/database"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
