# Generated by Django 5.1.2 on 2024-10-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performed_piece',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
