# Generated by Django 5.1.2 on 2024-10-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_performed_piece_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='performed_piece',
            name='arranger',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='performed_piece',
            name='event',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
