# Generated by Django 5.1.2 on 2024-11-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_instrumentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='categorized_instruments', to='performances.instrumentcategory'),
        ),
    ]
