# Generated by Django 5.1.2 on 2024-12-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_instruments_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='performed_piece',
            new_name='PerformedPiece',
        ),
    ]
