# Generated by Django 5.1.2 on 2024-12-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_instruments_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
