# Generated by Django 5.1.2 on 2024-12-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0007_rename_performed_piece_performedpiece'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Performers',
            new_name='Performer',
        ),
    ]
