# Generated by Django 5.1.2 on 2024-12-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0002_composition_complete'),
        ('performances', '0008_rename_performers_performer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='instruments',
            new_name='Instrument',
        ),
    ]
