# Generated by Django 5.1.2 on 2024-12-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0009_rename_instruments_instrument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentcategory',
            options={'verbose_name': 'Instrument Category', 'verbose_name_plural': 'Instrument Categories'},
        ),
    ]
