# Generated by Django 5.1.2 on 2024-12-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0010_alter_instrumentcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='performedpiece',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
