# Generated by Django 5.1.2 on 2024-11-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performances', '0006_instruments_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('og_composer', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('piece_type', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='')),
                ('instruments', models.ManyToManyField(related_name='composed_pieces', to='performances.instruments')),
            ],
        ),
    ]
