# Generated by Django 5.1.2 on 2024-11-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
