"""
urls.py
Reagan Zierke <reaganzierke@gmail.com>
12-03-2024
Creates the urls for the composition part of the site. The slug field is also autogenerated here.
"""
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="rz_composition_index"),
    path("<slug:slug>/", views.composition, name="composition"),
]